name: CI/CD Pipeline for Auth Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t auth-service .
          docker tag auth-service:latest 326061183428.dkr.ecr.us-east-2.amazonaws.com/auth-service:latest

      - name: Push Docker image to ECR
        run: |
          docker push 326061183428.dkr.ecr.us-east-2.amazonaws.com/auth-service:latest

      - name: Register new task definition revision
        id: register-task
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --family auth-service-task \
            --execution-role-arn arn:aws:iam::326061183428:role/ecsTaskExecutionRole \
            --requires-compatibilities FARGATE \
            --network-mode awsvpc \
            --cpu 512 \
            --memory 1024 \
            --container-definitions "$(aws ecs describe-task-definition --task-definition auth-service-task --query 'taskDefinition.containerDefinitions' --output json | sed "s|326061183428.dkr.ecr.us-east-2.amazonaws.com/auth-service:.*|326061183428.dkr.ecr.us-east-2.amazonaws.com/auth-service:latest|")" \
            --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "task_definition_arn=$TASK_DEF_ARN" >> $GITHUB_OUTPUT

      - name: Deploy to Amazon ECS via AWS CLI
        run: |
          aws ecs update-service \
            --cluster my-microservices-cluster \
            --service auth-service-task-service-3zr46qju \
            --task-definition ${{ steps.register-task.outputs.task_definition_arn }}
